dashboard:
  - apps/dashboard/**

api:
  - apps/api/**

docs:
  - apps/docs/**
  - "**/*.md"
  - "**/*.mdx"

config:
  - .github/**
  - turbo.json
  - pnpm-workspace.yaml
  - package.json
  - configs/**
  - .eslintrc*
  - .prettierrc*
  - .editorconfig

infra:
  - docker-compose.yml
  - Dockerfile
  - .dockerignore

shared:
  - packages/**
  - configs/**

testing:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/__tests__/**"

types:
  - "**/*.d.ts"
  - types/**

styles:
  - "**/*.css"
  - "**/*.scss"
  - "**/*.sass"
  - "**/*.tailwind.css"
