name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push API Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f apps/api/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/cps-task-manager-api:latest \
            --push .

      - name: Build and Push Dashboard Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f apps/dashboard/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/cps-task-manager-dashboard:latest \
            --push .
